/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class GiangVienForm extends javax.swing.JFrame {
    private GiangVienQuanLyDiem quanlydiem;
    private GiangVienLopHoc lophoc;
    private GiangVienHuongDanSuDungPanel huongdansudung;
    private JPanel childPanel;
    
    /**
     * Creates new form GiangVienForm
     */
    public GiangVienForm() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(WIDTH, HEIGHT);
        this.pack();
        this.setFocusable(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }
    private void showPanel(JPanel panel){
        childPanel = panel;
        giangVienPanel.removeAll();
        giangVienPanel.add(childPanel);
        giangVienPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lopHocButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        quanLyDiemButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        huongDanSuDungButton = new javax.swing.JButton();
        giangVienPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jToolBar1.setRollover(true);

        lopHocButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-document-edit-icon-32.png"))); // NOI18N
        lopHocButton.setText("Lớp học");
        lopHocButton.setFocusable(false);
        lopHocButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lopHocButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lopHocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lopHocButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(lopHocButton);
        jToolBar1.add(jSeparator1);

        quanLyDiemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon-32.png"))); // NOI18N
        quanLyDiemButton.setText("Quản lý điểm");
        quanLyDiemButton.setFocusable(false);
        quanLyDiemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quanLyDiemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quanLyDiemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyDiemButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(quanLyDiemButton);
        jToolBar1.add(jSeparator2);

        huongDanSuDungButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-help-about-icon-32.png"))); // NOI18N
        huongDanSuDungButton.setText("Hướng dẫn sử dụng");
        huongDanSuDungButton.setFocusable(false);
        huongDanSuDungButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        huongDanSuDungButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        huongDanSuDungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huongDanSuDungButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(huongDanSuDungButton);

        giangVienPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(giangVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(giangVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lopHocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lopHocButtonActionPerformed
        showPanel(new GiangVienLopHoc());
    }//GEN-LAST:event_lopHocButtonActionPerformed

    private void quanLyDiemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyDiemButtonActionPerformed
        showPanel(new GiangVienQuanLyDiem());
    }//GEN-LAST:event_quanLyDiemButtonActionPerformed

    private void huongDanSuDungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huongDanSuDungButtonActionPerformed
        showPanel(new GiangVienHuongDanSuDungPanel());
    }//GEN-LAST:event_huongDanSuDungButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiangVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel giangVienPanel;
    private javax.swing.JButton huongDanSuDungButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton lopHocButton;
    private javax.swing.JButton quanLyDiemButton;
    // End of variables declaration//GEN-END:variables
}
