/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentmanagementsystem;

import static java.awt.image.ImageObserver.HEIGHT;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class SinhVienForm extends javax.swing.JFrame {
    private SinhVienDangKyHocPhanPanel dangkyhocphan;
    private SinhVienXemDiemPanel xemdiem;
    private SinhVienHuongDanSuDungPanel huongdansudung;
    private JPanel childPanel;
    
    private void showPanel(JPanel panel){
        childPanel = panel;
        sinhVienPanel.removeAll();
        sinhVienPanel.add(childPanel);
        sinhVienPanel.validate();
    }

    /**
     * Creates new form SinhVienForm
     */
    public SinhVienForm() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setSize(WIDTH, HEIGHT);
        this.pack();
        this.setFocusable(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        xemDiemButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        dangKyHocPhanButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        huongDanSuDungButton = new javax.swing.JButton();
        sinhVienPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        xemDiemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gpa-icon-24.png"))); // NOI18N
        xemDiemButton.setText("Xem điểm");
        xemDiemButton.setFocusable(false);
        xemDiemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xemDiemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        xemDiemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xemDiemButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(xemDiemButton);
        jToolBar1.add(jSeparator1);

        dangKyHocPhanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Actions-view-choose-icon-24.png"))); // NOI18N
        dangKyHocPhanButton.setText("Đăng ký học phần");
        dangKyHocPhanButton.setFocusable(false);
        dangKyHocPhanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dangKyHocPhanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dangKyHocPhanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangKyHocPhanButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(dangKyHocPhanButton);
        jToolBar1.add(jSeparator2);

        huongDanSuDungButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search-icon-24.png"))); // NOI18N
        huongDanSuDungButton.setText("Hướng dẫn sử dụng");
        huongDanSuDungButton.setFocusable(false);
        huongDanSuDungButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        huongDanSuDungButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        huongDanSuDungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                huongDanSuDungButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(huongDanSuDungButton);

        sinhVienPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sinhVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sinhVienPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xemDiemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xemDiemButtonActionPerformed
        showPanel(new SinhVienXemDiemPanel());
    }//GEN-LAST:event_xemDiemButtonActionPerformed

    private void dangKyHocPhanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangKyHocPhanButtonActionPerformed
        showPanel(new SinhVienDangKyHocPhanPanel());
    }//GEN-LAST:event_dangKyHocPhanButtonActionPerformed

    private void huongDanSuDungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_huongDanSuDungButtonActionPerformed
        showPanel(new SinhVienHuongDanSuDungPanel());
    }//GEN-LAST:event_huongDanSuDungButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangKyHocPhanButton;
    private javax.swing.JButton huongDanSuDungButton;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel sinhVienPanel;
    private javax.swing.JButton xemDiemButton;
    // End of variables declaration//GEN-END:variables
}
